package vista;

import controlador.ControladorPrincipal;

/**
 *
 * @author Lanfor, Profe ya entendí como hacerlo bien, para la proxima vez
 */
public class FRM_VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FRM_VentanaPrincipal
     */
    
    
    ControladorPrincipal controlador;
    
    public FRM_VentanaPrincipal() {
        super("Sistema de matricula UCR");
        setLocation(300, 150);
        initComponents();
        controlador=new ControladorPrincipal();
        agregarEvento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_Registro = new javax.swing.JMenu();
        jm_Estudiante = new javax.swing.JMenuItem();
        jm_cursos = new javax.swing.JMenuItem();
        jm_Matricula = new javax.swing.JMenu();
        jm_RegistrarMatricula = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jm_Salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N

        jm_Registro.setText("Registro");

        jm_Estudiante.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jm_Estudiante.setText("estudiantes");
        jm_Registro.add(jm_Estudiante);

        jm_cursos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jm_cursos.setText("cursos");
        jm_Registro.add(jm_cursos);

        jMenuBar1.add(jm_Registro);

        jm_Matricula.setText("Matricula");

        jm_RegistrarMatricula.setText("Registrar");
        jm_Matricula.add(jm_RegistrarMatricula);

        jMenuBar1.add(jm_Matricula);

        jMenu1.setText("Reportes");
        jMenuBar1.add(jMenu1);

        jm_Salir.setText("Salir");
        jMenuBar1.add(jm_Salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void agregarEvento()    {
        jm_Estudiante.addActionListener(controlador);
        jm_cursos.addActionListener(controlador);
        jm_RegistrarMatricula.addActionListener(controlador);
        jm_Salir.addActionListener(controlador);
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jm_Estudiante;
    private javax.swing.JMenu jm_Matricula;
    private javax.swing.JMenuItem jm_RegistrarMatricula;
    private javax.swing.JMenu jm_Registro;
    private javax.swing.JMenu jm_Salir;
    private javax.swing.JMenuItem jm_cursos;
    // End of variables declaration//GEN-END:variables
}
