package vista;

import controlador.Controlador_VentanaRegistroCursos;
import javax.swing.JOptionPane;
import modelo.ArrayCurso;
import modelo.Curso;

/**
 *
* @author Lanfor, Profe ya entendí como hacerlo bien, para la proxima vez
 */
public class FRM_VentanaRegistroCursos extends javax.swing.JFrame {

    /**
     * Creates new form FRM_VentanaRegistroCursos
     */
    Controlador_VentanaRegistroCursos controlador;
    ArrayCurso array;
    FRM_VentanaInformativa frm_VentanaInformativa=new FRM_VentanaInformativa();
    public FRM_VentanaRegistroCursos() {
        super("Regsitro de cursos UCR");
        initComponents();
        setVisible(false);
        setLocation(450, 200);
        controlador=new Controlador_VentanaRegistroCursos(this);
        array=new ArrayCurso();
        this.panel_Botones1.generarEvento(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Botones1 = new vista.Panel_Botones();
        panel_InformacionBasica1 = new vista.Panel_InformacionBasica();
        jl_Imagen = new javax.swing.JLabel();

        setTitle("Regsitro de Cursos UCR");
        setResizable(false);

        jl_Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/firma-ucr-ico.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_InformacionBasica1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jl_Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_InformacionBasica1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void buscar()
    {
        if(array.verificar(panel_InformacionBasica1.obtenerInformacion()[2])!=null)
        {
            Curso objeto=array.verificar(panel_InformacionBasica1.obtenerInformacion()[2]);
            panel_Botones1.habilitacionBotones(1);
            panel_InformacionBasica1.habilitarEspacios(true);
            panel_InformacionBasica1.establecerInformacion(objeto.getNombre(), "", objeto.getSiglas(), Integer.toString(objeto.getCreditos()));
        }
        else 
        {
            panel_Botones1.habilitacionBotones(2);
            panel_InformacionBasica1.habilitarEspacios(true);
            frm_VentanaInformativa.establecerInformacion(array.getInformacion());
        }
    }
     public void agregar()
    {
        String[] informacion=panel_InformacionBasica1.obtenerInformacion();
        if(informacion[0].equals("")||informacion[2].equals("")||informacion[3].equals(""))
        {
            JOptionPane.showMessageDialog(this,"Información imcompleta","ERROR!!!",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            if(array.verificar(panel_InformacionBasica1.obtenerInformacion()[2])!=null)
            {
                JOptionPane.showMessageDialog(this,"Estas siglas ya se encuentra"
                +" en el registro","ERROR!!!",JOptionPane.ERROR_MESSAGE);
                panel_Botones1.habilitacionBotones(3);
                panel_InformacionBasica1.habilitarEspacios(false);
            }
            else
            {
                Curso objeto=new Curso(panel_InformacionBasica1.obtenerInformacion()[0], panel_InformacionBasica1.obtenerInformacion()[2], Integer.parseInt(panel_InformacionBasica1.obtenerInformacion()[3]));
                array.agregar(objeto);
                panel_Botones1.habilitacionBotones(3);
                panel_InformacionBasica1.habilitarEspacios(false);
                JOptionPane.showMessageDialog(this, "Proceso Exitoso");
                panel_InformacionBasica1.establecerInformacion("", "", "", "");
            }
        }
    }
     public ArrayCurso getArray()
     {
         return array;
     }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jl_Imagen;
    private vista.Panel_Botones panel_Botones1;
    private vista.Panel_InformacionBasica panel_InformacionBasica1;
    // End of variables declaration//GEN-END:variables
}
