/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_VentanaRegistroCursos;
import controlador.Controlador_VentanaRegistroEstudiantes;
import javax.swing.JOptionPane;

/**
 *
 * @author Lanfor
 */
public class Panel_Botones extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Botones
     */
    public Panel_Botones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Agregar = new javax.swing.JButton();
        btn_Buscar = new javax.swing.JButton();
        btn_Modificar = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();

        btn_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar.png"))); // NOI18N
        btn_Agregar.setText("Agregar");
        btn_Agregar.setEnabled(false);

        btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        btn_Buscar.setText("Buscar");

        btn_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificar.png"))); // NOI18N
        btn_Modificar.setText("Modificar");
        btn_Modificar.setEnabled(false);

        btn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Agregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Modificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Eliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Agregar)
                    .addComponent(btn_Buscar)
                    .addComponent(btn_Modificar)
                    .addComponent(btn_Eliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public  void generarEvento(Controlador_VentanaRegistroEstudiantes controlador)
    {
        btn_Agregar.addActionListener(controlador);
        btn_Buscar.addActionListener(controlador);
        btn_Eliminar.addActionListener(controlador);
        btn_Modificar.addActionListener(controlador);
    }
    
    public  void generarEvento(Controlador_VentanaRegistroCursos controlador)
    {
        btn_Agregar.addActionListener(controlador);
        btn_Buscar.addActionListener(controlador);
        btn_Eliminar.addActionListener(controlador);
        btn_Modificar.addActionListener(controlador);
    }
    
    public void habilitacionBotones(int habilitacion)
    {
        if(habilitacion==1)
        {
            btn_Agregar.setEnabled(false);
            btn_Buscar.setEnabled(true);
            btn_Modificar.setEnabled(true);
            btn_Eliminar.setEnabled(true);
        }        
        else
        {
            if(habilitacion==2)
            {
                btn_Agregar.setEnabled(true);
                btn_Buscar.setEnabled(true);
                btn_Modificar.setEnabled(false);
                btn_Eliminar.setEnabled(false);
            }
            else
            {
                btn_Agregar.setEnabled(false);
                btn_Buscar.setEnabled(true);
                btn_Modificar.setEnabled(false);
                btn_Eliminar.setEnabled(false);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Agregar;
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_Modificar;
    // End of variables declaration//GEN-END:variables
}
