/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_FRM_Principal;

/**
 *
 * @author Lanfor
 */
public class FRM_Principal extends javax.swing.JFrame {

    /**
     * Creates new form FRM_VentanaPrincipal
     */
    
    Controlador_FRM_Principal controlador_FRM_Principal;
    public FRM_Principal() 
    {
        initComponents();
        controlador_FRM_Principal=new Controlador_FRM_Principal(this);
        setLocation(300, 200);
        agregarEventos();
        colocarCodigo();
        mandarControlador();
        desabilitarCampos();
    }
    public void desabilitarCampos()
    {
        this.panel_Informacion1.desabilitarCampos();
    }
    public void habilitarCampos()
    {
        this.panel_Informacion1.habilitarCampos();
    }
    public void agregarEventos()
    {
       this.panel_Botones1.agregarEventos(controlador_FRM_Principal);
    }
    public void colocarCodigo()
    {
       this.panel_Informacion1.colocarCodigo(controlador_FRM_Principal.metodosBiblioteca.devolverCodigo());
    }
   public String devolverNumPrestamo()
    {
       return this.panel_Informacion1.devolverNumPrestamo();
    }
    public int mostrarMensajeOpcional(String msj)
    {
        return this.panel_Informacion1.mostrarMensajeOpcional(msj);
    }
    public void desabilitarBotones()
    {
        this.panel_Botones1.desabilitarBotones();
    }
    public void habilitarBotones()
    {
        this.panel_Botones1.habilitarBotones();
    }
    public void habilitarAgregar()
    {
        this.panel_Botones1.habilitarAgregar();
    }
    public void resetarVentana()
    {
        this.panel_Informacion1.resetearVentana();
        this.panel_Botones1.desabilitarBotones();
    }
    public void mostrarMensaje(String msj)
    {
        this.panel_Informacion1.mostarMensaje(msj);
    }
    public void mandarControlador()
    {
        this.panel_Informacion1.recibirControlador(controlador_FRM_Principal);
    }
    public void colocarInformacion(String[] informacion)
    {
        this.panel_Informacion1.colocarInformacion(informacion);
    }
    public String[] informacionFormulario()
    {
        return this.panel_Informacion1.informacionFormulario();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Botones1 = new vista.Panel_Botones();
        panel_Informacion1 = new vista.Panel_Informacion();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_Informacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel_Informacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.Panel_Botones panel_Botones1;
    private vista.Panel_Informacion panel_Informacion1;
    // End of variables declaration//GEN-END:variables
}
